SERVICE_URL = 'https://www.symphony-solutions.eu/'
CONTACT_FORM_URL = 'https://www.symphony-solutions.eu/contact-us/'
STANDBY_UKRAINE = 'https://standby-ukraine.com/'

WRONG_URL_AFTER_SLASH = ['test', 'test/', 'contact-us/test', ]

WRONG_URL_HTTPS = ['http://symphony-solutions.eu',
                   'http://symphony-solutions.eu',
                   'http://www.symphony-solutions.eu', ]

XML_URL = 'https://symphony-solutions.eu/sitemap.xml'

ALL_POST_URL = ['blog/',
                'symphony-summer-hiring-nigeria/',
                'symphony-personas-yinka-akinbobola/',
                'symphony-personas-ibironke-yekinni/',
                'symphony-personas-gordana-andonovska/',
                'symphony-solutions-supports-ukraine-spring-initiatives/',
                'java-trends-and-technologies/',
                'definitive-guide-to-vertx/',
                'java-12-17-features/',
                'tech-world-meets-animal-conservation/',
                'symphony-personas-in-tech-oleksandr-hrechnikov/',
                'what-workation-at-symphony-is-like/',
                'symphony-personas-martin-kubelka/',
                'java-meetup/',
                'regulation-and-responsible-gaming/',
                'python-security-best-practices-webinar/',
                'open-day-at-symphony-solutions/',
                'preparing-to-client-interview-checklist/',
                'mobile-application-testing-guide/',
                'istqb-foundation-exam-preparation-course/',
                'symphony-personals-wojciech-dziadura/',
                'symphony-personas-andriy-pestov/',
                'react-in-the-front-end-world-practical-cases/',
                'work-or-vacation-how-about-workation/',
                'fixing-memory-leaks-in-android/',
                'symphonian-starter-pack-what-youre-gonna-get/',
                'how-to-prepare-for-and-pass-istqb-certification/',
                'motivated-remote-team-webinar/',
                'symphony-personas-filip-kudron/',
                'symphony-personas-slawomir-umpirowicz/',
                'symphony-personas-oleg-chekan/',
                'symphony-personas-oksana-yaroshko/',
                'how-to-become-a-full-stack-developer/',
                'symphony-personas-sanja-jovanovikj/',
                'csr-annual-report-essential-part-of-company-focus-in-2020/',
                'symphony-personas-aleksandar-gacevski/',
                'dou-names-symphony-solutions-among-best-it-employers-in-ukraine-2020/',
                'the-importance-of-self-care-interview-with-corporate-psychologists/',
                'design-thinking-online-workshop/',
                'say-nomore-to-domestic-violence/',
                'project-change-management-webinar/',
                'initiating-change-react-upskilling-for-colleagues/',
                'virtual-office-symphony-anywhere/',
                'react-hooks-2020/',
                'working-from-home/',
                'how-can-artificial-intelligence-help-in-ivf/',
                'symphony-solutions-to-attend-ice-london-2020/',
                'ai-and-igaming-come-together-case-study/',
                'relocate-to-poland-with-symphony-solutions/',
                'clutch-names-symphony-solutions-as-a-top-software-developer/',
                'symphony-solutions-among-the-20-most-promising-devops-solution-providers-of-2019/',
                'write-code-like-music-symphony-solutions-unveils-new-branding/',
                'blexr-agile-transformation-case-study/',
                '172nd-grand-national-a-remarkable-experience/',
                'north-macedonia-only-5-of-leadership-roles-held-by-women/',
                'symphony-solutions-comes-to-boston/',
                'symphony-solutions-turns-10-here-is-how-we-celebrated/',
                'featured-client-ladbrokes-coral/',
                'how-a-dutchman-opened-an-it-business-in-ukraine/',
                'silicon-review-names-symphony-solutions-among-the-50-best-workplaces-of-2018/',
                'who-is-she/',
                'symphony-solutions-among-insights-success-20-most-admired-companies-to-watch-in-2018/',
                'gender-balance/',
                'jdd-java-everyone/',
                'kindhack-skopje-coding-charity/',
                'lviv-trip-program/',
                'symphony-solutions-largest-client-upgrades-to-angular-6/',
                'clutch-recognizes-symphony-solutions-top-b2b-company/',
                'netherlands-in-krakow/',
                'coral-case-study/',
                'excited-announce-launch-new-agile-space-website/',
                'relocate-new-office-krakow/',
                'whats-next-for-women/',
                'symphonians-participate-marathon-races/',
                'latest-trends-java-technology-2018/',
                'hologram-pyramid-project-case-study/',
                'best-programming-languages-learn-2018/',
                'kindhack-coding-for-charity/',
                'new-partnership-delivery-center-in-krakow/',
                'symphony-solutions-among-50-best-workplaces-of-2017/',
                'agile-transformation-company-2017-award/',
                'join-symphony-solutions-krakow-win-trip-bali/',
                'software-architecture-for-engineers/',
                'symphony-solutions-is-a-friend-of-lviv-mozart-festival/',
                'symphony-solutions-open-new-office-krakow-poland/',
                'symphony-solutions-became-a-google-partner/',
                'values-that-shape-our-corporate-culture/',
                'symphony-solutions-at-codefest-in-ohrid-macedonia/',
                'video-celebration-5-anniversary-as-symphonian-to-the-netherlands/',
                'charity-hackaton-kindhack-at-symphony-solutions/',
                'green-week-at-symphony-solutions/',
                'symphony-solutions-poland-new-office/',
                '20-most-promising-quality-assurance-solution-providers-2016/',
                'why-working-at-symphony-solutions-is-almost-the-bahamas/',
                'career-it-in-rzeszow/',
                'new-office-in-macedonia/',
                'symphony-solution-recognized-by-cio-review-as-20-most-promising-java-development-solution-providers/',
                'create-your-own-robot/',
                'dou-inspector-in-lviv-little-holland-in-symphony-solutions-office/',
                'symphony-solutions-opened-a-new-office-in-rzeszow/',
                'symphony-solutions-opened-a-new-office-in-macedonia/',
                'theo-schnitfink-it-lviv/',
                'ukrainian-it-professionals-are-2nd-best-in-the-world/',
                'ukraine-ranks-13th-by-science-and-technology-capabilities/',
                'ukraine-is-fourth-in-world-by-number-of-it-specialists/',
                'ukraine-in-top30-gartners-countries-for-offshore-and-nearshore-services/',
                'lviv-it-cluster-in-ukraine-leads-the-efforts-to-boost-it-talent-pool/',
                'regional-structure-of-ukraines-it-outsourcing-industry/',
                'sports-betting-app-development-features/',
                'symphony-solutions-supports-national-rehabilitation-center-of-ukraine/', ]

ALL_MAIN_PAGE_URL = ['',
                     'who-we-are/',
                     'contact-us/',
                     'who-we-are/our-awards-and-recognitions/',
                     'who-we-are/symphony-academy/',
                     'who-we-are/agile/',
                     'who-we-are/culture/',
                     'mr-cannabis-harantuie-naikrutishi-benefity/',
                     'devops-school/',
                     'casumo-project/',
                     'hpe-project/',
                     'vivino-project/',
                     'indegene-project/',
                     'symphony-anywhere/',
                     'react-career/',
                     'william-hill-project/',
                     'avantage-project/',
                     'client-ladbrokes-coral-group/',
                     'omp-project/',
                     'perekhod-na-golang/',
                     'hansecom-project/',
                     'privacy-policy/',
                     'who-we-are/symphony-care/',
                     'pay-per-head-project/',
                     'stand-by-ukraine/',
                     'benefits-anywhere/',
                     'benefits-in-north-macedonia/',
                     'benefits-in-poland/',
                     'benefits-in-ukraine/',
                     'quick-apply/',
                     'featured-client-covizmo/',
                     'symphony-nigeria-summer-hiring/',
                     'nigeria-remote-vacancies/', ]

ALL_VACANCIES_URL = ['vacancies/',
                     'vacancy/senior-full-stack-developer-anywhere/',
                     'vacancy/middle-senior-data-engineer-anywhere/',
                     'vacancy/middle-fullstack-engineer-react-nodejs-anywhere/',
                     'vacancy/senior-business-analyst-poland-2/',
                     'vacancy/senior-business-analyst-poland/',
                     'vacancy/senior-data-engineer-anywhere/',
                     'vacancy/qa-engineer-anywhere/',
                     'vacancy/senior-drupal-themer-poland-ukraine/',
                     'vacancy/sitecore-support-engineer-poland-ukraine-remote/',
                     'vacancy/lead-sitecore-developer-poland-ukraine/',
                     'vacancy/lead-full-stack-vue-node-remote/',
                     'vacancy/senior-full-stack-php-developer-nigeria/',
                     'vacancy/senior-talent-acquisition-marketing-specialist-nigeria/',
                     'vacancy/sap-abab-poland/',
                     'vacancy/sap-sd-otc-poland/',
                     'vacancy/senior-developer-anywhere/',
                     'vacancy/senior-java-software-engineer-anywhere/',
                     'vacancy/middle-python-developer-anywhere/',
                     'vacancy/senior-scrum-master-anywhere-3/',
                     'vacancy/java-tech-lead-anywhere/',
                     'vacancy/head-corporate-recruitment-anywhere/',
                     'vacancy/senior-multi-channel-marketing-manager-anywhere/',
                     'vacancy/aws-php-system-architect-ukraine/',
                     'vacancy/middle-php-developer-ukraine/',
                     'vacancy/junior-middle-java-software-engineer-anywhere/',
                     'vacancy/middle-ba-anywhere/',
                     'vacancy/senior-manual-qa-anywhere/',
                     'vacancy/senior-java-engineer-anywhere-2/',
                     'vacancy/salesforce-marketing-cloud-lead-anywhere/',
                     'vacancy/middle-senior-fullstack-engineer-node-anywhere/',
                     'vacancy/junior-java-software-engineer-anywhere/',
                     'vacancy/middle-devops-poland-ukraine/',
                     'vacancy/middle-senior-dotnet-developer-ukraine/',
                     'vacancy/middle-seo-specialist-nigeria/',
                     'vacancy/senior-ld-specialist-ukraine-anywhere/',
                     'vacancy/senior-aqa-anywhere-4/',
                     'vacancy/senior-people-partner-nigeria/',
                     'vacancy/lead-ul-ux-designer-nigeria/',
                     'vacancy/middle-manual-automation-qa-nigeria/',
                     'vacancy/aws-backend-platform-architect-ukraine/',
                     'vacancy/middle-senior-sdet/', ]

ALL_COUNTRY_URL = ['country/brazil/',
                   'country/macedonia/',
                   'country/nigeria/',
                   'country/poland/',
                   'country/ukraine/', ]

ALL_VACANCIES_CATEGORY_URL = ['vacancies-brazil/',
                              'vacancies-macedonia/',
                              'vacancies-nigeria/',
                              'vacancies-poland/',
                              'vacancies-anywhere/',
                              'vacancies-ukraine/', ]
